endpoints:
  metrics:
    enabled: true
    sensitive: false

vcap:
  application:
    name: unknown
    cf-api: http://example.com
    space-id: unknown

cf:
  username: nope@nope.com
  password: unknown

logmon:
  consumption:
    post-production-wait-time-millis: 10000
  production:
    logs-per-test: 10000

---

spring:
  profiles: dev
  thymeleaf:
    cache: false

vcap:
  application:
    name: cf-logmon
    cf-api: https://api.run.pez.pivotal.io
    space-id: 92340jkjd09j293ej

cf:
  username: ttaylor+cf-logmon@pivotal.io
  password: FAIL
